import {beforeEach,afterEach,describe,it,expect,vi} from "vitest";
import {adminVoiceSettings} from "./enrollment";
import type {BridgeLocal} from "../core/bridge-local";
import {setLanguage} from "../core/i18n";
function bridge(){return{speakerStatus:vi.fn(async()=>({enrolled:false,enrolling:false})),speakerEnrollmentBegin:vi.fn(async()=>({enrolled:false,enrolling:true})),speakerEnrollmentEnd:vi.fn(async()=>({enrolled:false,enrolling:false})),speakerEnroll:vi.fn(async(_wav:string,_requestId:string)=>({enrolled:true,enrolling:true})),speakerClear:vi.fn(async()=>{}),cancel:vi.fn(async()=>{})};}
async function flush(){for(let i=0;i<12;i++)await Promise.resolve();}
function capture(){const stop=vi.fn(),close=vi.fn(async()=>{});const processor={connect:vi.fn(),disconnect:vi.fn(),onaudioprocess:null as ((event:AudioProcessingEvent)=>void)|null};vi.stubGlobal("navigator",{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop}]})}});vi.stubGlobal("AudioContext",class{sampleRate=16000;state="running";destination={};resume=async()=>{};close=close;createMediaStreamSource=()=>({connect:vi.fn(),disconnect:vi.fn()});createScriptProcessor=()=>processor;});return{processor,stop,send:(seconds=1,amplitude=.05)=>processor.onaudioprocess?.({inputBuffer:{getChannelData:()=>new Float32Array(16000*seconds).fill(amplitude)}} as unknown as AudioProcessingEvent)};}
describe("admin enrollment lifecycle",()=>{
 beforeEach(()=>setLanguage("en"));afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();document.body.replaceChildren();});
 it("fails missing audio callbacks visibly, releases capture and never saves an empty profile",async()=>{
  vi.useFakeTimers();const input=capture(),api=bridge(),ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);ui.el.querySelector<HTMLButtonElement>(".actions button")!.click();await flush();await vi.advanceTimersByTimeAsync(3100);await flush();
  expect(api.speakerEnroll).not.toHaveBeenCalled();expect(input.stop).toHaveBeenCalledOnce();expect(ui.el.textContent).toContain("No microphone audio arrived");expect(ui.el.querySelector<HTMLButtonElement>(".actions button")!.disabled).toBe(false);ui.dispose();
 });
 it("uses measured input for level/progress and never submits a partial recording at the wall deadline",async()=>{
  vi.useFakeTimers();const input=capture(),api=bridge(),ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);ui.el.querySelector<HTMLButtonElement>(".actions button")!.click();await flush();
  for(let i=0;i<10;i++){input.send();await vi.advanceTimersByTimeAsync(1500);}
  expect(ui.el.querySelector<HTMLMeterElement>(".input-meter meter")!.value).toBeCloseTo(.4);expect(ui.el.querySelector<HTMLProgressElement>(".admin-voice-progress progress")!.value).toBe(10);
  await vi.advanceTimersByTimeAsync(1100);await flush();expect(api.speakerEnroll).not.toHaveBeenCalled();expect(ui.el.textContent).toContain("No microphone audio arrived");expect(input.stop).toHaveBeenCalledOnce();ui.dispose();
 });
 it("rejects silent PCM locally with actionable feedback instead of saving a profile",async()=>{
  const input=capture(),api=bridge(),ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);ui.el.querySelector<HTMLButtonElement>(".actions button")!.click();await flush();for(let i=0;i<12;i++)input.send(1,0);await flush();
  expect(api.speakerEnroll).not.toHaveBeenCalled();expect(ui.el.textContent).toContain("No clear speech");expect(input.stop).toHaveBeenCalledOnce();ui.dispose();
 });
 it("cancel clears the input watchdog and preserves only discarded PCM",async()=>{
  vi.useFakeTimers();const input=capture(),api=bridge(),ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);const buttons=ui.el.querySelectorAll<HTMLButtonElement>(".actions button");buttons[0].click();await flush();input.send();buttons[1].click();await flush();await vi.advanceTimersByTimeAsync(20000);
  expect(api.speakerEnroll).not.toHaveBeenCalled();expect(input.stop).toHaveBeenCalledOnce();expect(ui.el.textContent).not.toContain("No microphone audio arrived");expect(vi.getTimerCount()).toBe(0);ui.dispose();
 });
 it("shows a truthful integer PCM recording progress fixture without activating media",()=>{const ui=adminVoiceSettings(false,undefined,{enrolled:false,enrolling:true,recordedSeconds:7});const progress=ui.el.querySelector<HTMLProgressElement>("progress")!;expect(progress.value).toBe(7);expect(progress.max).toBe(12);expect(ui.el.textContent).toContain("7 of 12 seconds");expect(ui.el.textContent).toContain("Recording time");expect(ui.el.textContent).toContain("Microphone input level");expect(ui.el.querySelector<HTMLButtonElement>(".actions button")!.hidden).toBe(true);expect(ui.el.textContent).toContain("Cancel recording");expect(ui.el.querySelector<HTMLButtonElement>(".actions button")!.disabled).toBe(true);ui.dispose();});
  it("keeps recording instructions and current status visible while description is disclosed",()=>{const ui=adminVoiceSettings(false,undefined,{enrolled:true,enrolling:false});const panel=ui.el.querySelector<HTMLElement>(".settings-help-content")!;expect(panel.hidden).toBe(true);expect(ui.el.querySelector('[role="status"]')!.textContent).toContain("Admin voice registered");expect(ui.el.querySelector(".hint")!.textContent).toContain("12");ui.el.querySelector<HTMLButtonElement>(".settings-help-button")!.click();expect(panel.hidden).toBe(false);ui.dispose();});
 it("never acquires preview microphone",()=>{const media=vi.fn();vi.stubGlobal("navigator",{mediaDevices:{getUserMedia:media}});const ui=adminVoiceSettings(false,undefined,{enrolled:true,enrolling:false});ui.el.querySelector<HTMLButtonElement>(".actions button")!.click();expect(media).not.toHaveBeenCalled();expect(ui.el.textContent).toContain("Admin voice registered");ui.dispose();});
 it("pauses global listening before requesting permission and restores on denied input",async()=>{const api=bridge();const media=vi.fn(async()=>{expect(api.speakerEnrollmentBegin).toHaveBeenCalledOnce();throw new DOMException("Denied","NotAllowedError");});vi.stubGlobal("navigator",{mediaDevices:{getUserMedia:media}});const ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);ui.el.querySelector<HTMLButtonElement>(".actions button")!.click();await flush();expect(api.speakerEnrollmentEnd).toHaveBeenCalled();expect(api.speakerEnroll).not.toHaveBeenCalled();expect(ui.el.textContent).toContain("Microphone access was denied");ui.dispose();});
 it("cancelling a pending permission releases the late stream without enrolling",async()=>{const api=bridge();let done:(stream:MediaStream)=>void=()=>{};const stop=vi.fn();vi.stubGlobal("navigator",{mediaDevices:{getUserMedia:()=>new Promise(resolve=>done=resolve)}});const ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);const buttons=ui.el.querySelectorAll<HTMLButtonElement>(".actions button");buttons[0].click();await flush();buttons[1].click();done({getTracks:()=>[{stop}]} as unknown as MediaStream);await flush();expect(stop).toHaveBeenCalledOnce();expect(api.speakerEnrollmentEnd).toHaveBeenCalled();expect(api.speakerEnroll).not.toHaveBeenCalled();ui.dispose();});
 it("submits only bounded PCM audio, releases capture, and finishes the enrollment lock",async()=>{const api=bridge();const stop=vi.fn();const close=vi.fn(async()=>{});const processor={connect:vi.fn(),disconnect:vi.fn(),onaudioprocess:null as ((event:AudioProcessingEvent)=>void)|null};vi.stubGlobal("navigator",{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop}]})}});vi.stubGlobal("AudioContext",class{sampleRate=16000;state="running";destination={};resume=async()=>{};close=close;createMediaStreamSource=()=>({connect:vi.fn(),disconnect:vi.fn()});createScriptProcessor=()=>processor;});const ui=adminVoiceSettings(true,api as unknown as typeof BridgeLocal);ui.el.querySelector<HTMLButtonElement>(".actions button")!.click();await flush();for(let i=0;i<48;i++)processor.onaudioprocess?.({inputBuffer:{getChannelData:()=>new Float32Array(4096).fill(.05)}} as unknown as AudioProcessingEvent);await flush();expect(api.speakerEnroll).toHaveBeenCalledOnce();const wav=atob(api.speakerEnroll.mock.calls[0]![0] as string);expect(wav.length).toBe(44+12*16000*2);expect(stop).toHaveBeenCalledOnce();expect(close).toHaveBeenCalledOnce();expect(api.speakerEnrollmentEnd).toHaveBeenCalled();expect(ui.el.textContent).toContain("Admin voice registered");ui.dispose();});
});
