import {describe,it,expect,vi,beforeEach} from "vitest";
import {localSettings} from "./settings";
import {BridgeLocal,type LocalRuntimeStatus} from "../core/bridge-local";
import {setLanguage} from "../core/i18n";
const events=vi.hoisted(()=>new Map<string,(status:LocalRuntimeStatus)=>void>());
vi.mock("../core/bridge",()=>({IS_TAURI:true,onEvent:async(name:string,callback:(status:LocalRuntimeStatus)=>void)=>{events.set(name,callback);return()=>events.delete(name);}}));
const ready:LocalRuntimeStatus={ready:true,enabled:true,phase:"ready",component:"",downloaded:1618154256,total:1618154256,error:null};
const flush=async()=>{for(let i=0;i<6;i++)await Promise.resolve();};
beforeEach(()=>{document.body.replaceChildren();events.clear();setLanguage("en");});
describe("integrated local setup",()=>{
 it("isolates byte progress left-to-right inside Persian labels",()=>{setLanguage("fa");const settings=localSettings({native:true,preview:true,initial:{...ready,ready:false,enabled:false,phase:"downloading",component:"brain",downloaded:600000000}});expect(settings.el.dir).toBe("rtl");const count=settings.el.querySelector<HTMLElement>("bdi.local-progress-count")!;expect(count.dir).toBe("ltr");expect(count.textContent).toBe("۵۷۲ / ۱٬۵۴۴ MB");expect(count.parentElement?.textContent).toContain("در حال دانلود");settings.dispose();});
 it("shows verified readiness and keeps it when an enable/disable change fails",async()=>{const enable=vi.fn(async()=>{throw new Error("disk unavailable");});const settings=localSettings({native:true,bridge:{...BridgeLocal,status:async()=>ready,enable}});document.body.append(settings.el);await flush();const toggle=[...settings.el.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent==="Disable local brain")!;toggle.click();expect(toggle.textContent).toBe("Disabling local brain…");await flush();expect(enable).toHaveBeenCalledWith(false);expect(settings.el.textContent).toContain("previous state was kept");expect(settings.el.querySelector(".local-readiness")?.textContent).toContain("enabled");expect(settings.el.textContent).not.toContain("Installation failed");settings.dispose();});
 it("updates real byte progress and cancels without pretending the runtime is ready",async()=>{const downloading={...ready,ready:false,enabled:false,phase:"downloading",component:"brain",downloaded:600000000};const cancelInstall=vi.fn(async()=>{});const settings=localSettings({native:true,bridge:{...BridgeLocal,status:async()=>downloading,cancelInstall}});document.body.append(settings.el);await flush();const progress=settings.el.querySelector("progress")!;expect(progress.value).toBe(600000000);expect(progress.max).toBe(ready.total);[...settings.el.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent==="Cancel download")!.click();await flush();expect(cancelInstall).toHaveBeenCalledOnce();events.get("local-runtime-progress")?.({...downloading,phase:"cancelled",component:"",error:null});expect(settings.el.querySelector(".local-readiness")?.textContent).toContain("cancelled");expect(progress.hidden).toBe(true);expect(settings.el.textContent).not.toContain("Installed and verified");settings.dispose();});
 it("provides an initial status retry and suppresses late progress after disposal",async()=>{const status=vi.fn().mockRejectedValueOnce(new Error("unavailable")).mockResolvedValue(ready);const settings=localSettings({native:true,bridge:{...BridgeLocal,status}});document.body.append(settings.el);await flush();expect(settings.el.textContent).toContain("Could not check");[...settings.el.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent==="Check again")!.click();await flush();expect(settings.el.querySelector(".local-readiness")?.textContent).toContain("enabled");const callback=events.get("local-runtime-progress")!;settings.dispose();callback({...ready,enabled:false});expect(settings.el.querySelector(".local-readiness")?.textContent).toContain("enabled");});
 it("makes preview setup actions read-only",()=>{const install=vi.fn();const settings=localSettings({native:true,preview:true,initial:{...ready,ready:false,enabled:false,phase:"not-installed"},bridge:{...BridgeLocal,install}});const button=[...settings.el.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent==="Download and install")!;expect(button.disabled).toBe(true);button.click();expect(install).not.toHaveBeenCalled();settings.dispose();});
});
