import {afterEach,describe,it,expect,vi} from "vitest";
import {pcmWav,inputLevels,LocalVoiceController,speakerNotice,type LocalVoiceOptions} from "./voice";
function recorded(options:Partial<LocalVoiceOptions>={}){
 const stop=vi.fn();const close=vi.fn(async()=>{});const processor={disconnect:vi.fn(),connect:vi.fn(),onaudioprocess:null as ((event:AudioProcessingEvent)=>void)|null};
 const context={sampleRate:16000,state:"running",resume:async()=>{},close,createMediaStreamSource:()=>({connect:vi.fn(),disconnect:vi.fn()}),createScriptProcessor:()=>processor,destination:{}} as unknown as AudioContext;
 const controller=new LocalVoiceController({media:{getUserMedia:async()=>({getTracks:()=>[{stop}]} as unknown as MediaStream)},context:()=>context,ask:async()=>"پاسخ",onState:()=>{},bridge:{cancel:async()=>{},transcribe:async()=>({text:"سلام"}),speak:vi.fn()},...options});
 return{controller,stop,close,processor,capture:(silent=false)=>processor.onaudioprocess?.({inputBuffer:{getChannelData:()=>new Float32Array(4096).fill(silent?0:.05)}} as unknown as AudioProcessingEvent)};
}
describe("offline voice lifecycle",()=>{
 afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
 it("measures real bounded RMS/peak and throttles meter callbacks independently of phase",async()=>{
  vi.useFakeTimers();const onLevel=vi.fn();const item=recorded({onLevel});await item.controller.start();for(let i=0;i<20;i++)item.capture();
  expect(onLevel).toHaveBeenCalledOnce();expect(onLevel.mock.calls[0][0].rms).toBeCloseTo(.05);expect(onLevel.mock.calls[0][0].peak).toBeCloseTo(.05);
  await vi.advanceTimersByTimeAsync(100);item.capture();expect(onLevel).toHaveBeenCalledTimes(2);await item.controller.end();expect(onLevel.mock.calls.at(-1)?.[0]).toEqual({rms:0,peak:0});
  expect(inputLevels(new Float32Array([0,1,-1]))).toEqual({rms:Math.sqrt(2/3),peak:1});expect(()=>inputLevels(new Float32Array([NaN]))).toThrow("invalid");
 });
 it("fails an audio graph that delivers no callbacks without invoking recognition",async()=>{
  vi.useFakeTimers();const transcribe=vi.fn();const item=recorded({bridge:{transcribe,speak:vi.fn(),cancel:vi.fn()}});await item.controller.start();await vi.advanceTimersByTimeAsync(3100);
  expect(item.controller.phase).toBe("error");expect(item.stop).toHaveBeenCalledOnce();expect(transcribe).not.toHaveBeenCalled();expect(vi.getTimerCount()).toBe(0);await item.controller.end();
 });
 it("cleans up invalid audio callbacks without throwing out of the native callback",async()=>{
  const item=recorded({onLevel:vi.fn()});await item.controller.start();expect(()=>item.processor.onaudioprocess?.({inputBuffer:{getChannelData:()=>new Float32Array([NaN])}} as unknown as AudioProcessingEvent)).not.toThrow();
  expect(item.controller.phase).toBe("error");expect(item.stop).toHaveBeenCalledOnce();await item.controller.end();
 });
 it("times out suspended audio startup and releases the acquired microphone",async()=>{
  vi.useFakeTimers();const stop=vi.fn(),close=vi.fn(async()=>{}),onState=vi.fn();const controller=new LocalVoiceController({ask:vi.fn(),onState,media:{getUserMedia:async()=>({getTracks:()=>[{stop}]} as unknown as MediaStream)},context:()=>({sampleRate:16000,state:"suspended",resume:()=>new Promise(()=>{}),close} as unknown as AudioContext)});
  const start=controller.start();await Promise.resolve();await vi.advanceTimersByTimeAsync(5000);await start;expect(controller.phase).toBe("error");expect(String(onState.mock.calls.at(-1)?.[0].error)).toContain("start-timeout");expect(stop).toHaveBeenCalledOnce();expect(close).toHaveBeenCalledOnce();await controller.end();
 });
 it("cancelling synchronously on recording does not arm a stale input watchdog",async()=>{
  vi.useFakeTimers();let item:ReturnType<typeof recorded>;item=recorded({onState:state=>{if(state.phase==="recording")void item.controller.end();}});await item.controller.start();await Promise.resolve();expect(vi.getTimerCount()).toBe(0);expect(item.controller.phase).toBe("idle");
 });
 it("speaks the actual task result and rearms continuous listening after playback",async()=>{
  vi.stubGlobal("URL",{createObjectURL:()=>"blob:voice-task",revokeObjectURL:vi.fn()});
  const bytes=pcmWav(new Float32Array(160),16000);const wavBase64=btoa(String.fromCharCode(...bytes));
  const audio={src:"",onended:null as ((event:Event)=>void)|null,onerror:null,play:vi.fn(async()=>{}),pause:vi.fn(),removeAttribute:vi.fn(),load:vi.fn()} as unknown as HTMLAudioElement;
  const speak=vi.fn(async(_text:string,_requestId:string)=>({wavBase64}));const ask=vi.fn(async()=>"This PC opened");
  const item=recorded({continuous:true,verify:async()=>({matched:true,ticket:"test-ticket"}),ask,audio:()=>audio,bridge:{cancel:async()=>{},transcribe:async()=>({text:"open This PC"}),speak}});
  await item.controller.start();for(let i=0;i<8;i++)item.capture();for(let i=0;i<4;i++)item.capture(true);await vi.waitFor(()=>expect(ask).toHaveBeenCalledOnce());
  expect(ask).toHaveBeenCalledWith("open This PC");expect(speak.mock.calls[0][0]).toBe("This PC opened");expect(audio.play).toHaveBeenCalledOnce();
  await vi.waitFor(()=>expect(audio.play).toHaveBeenCalledOnce());audio.onended?.(new Event("ended"));await vi.waitFor(()=>expect(item.controller.phase).toBe("recording"));await item.controller.end();
 });
 it("manual verified VAD finishes one utterance without rearming",async()=>{const ask=vi.fn(async()=>"");const speak=vi.fn();const item=recorded({continuous:true,rearm:()=>false,allowSilentReply:true,verify:async()=>({matched:true,ticket:"test"}),ask,bridge:{cancel:async()=>{},transcribe:async()=>({text:"ambient"}),speak}});await item.controller.start();for(let i=0;i<8;i++)item.capture();for(let i=0;i<4;i++)item.capture(true);await vi.waitFor(()=>expect(item.controller.phase).toBe("idle"));expect(ask).toHaveBeenCalledOnce();expect(speak).not.toHaveBeenCalled();expect(item.controller.active).toBe(false);await item.controller.end();});
 it("manual silence times out without transcription or a repeated microphone request",async()=>{vi.useFakeTimers();const transcribe=vi.fn();const item=recorded({continuous:true,rearm:()=>false,allowSilentReply:true,bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});await item.controller.start();for(let i=0;i<30;i++){item.capture(true);await vi.advanceTimersByTimeAsync(1000);}expect(item.controller.phase).toBe("idle");expect(transcribe).not.toHaveBeenCalled();expect(item.stop).toHaveBeenCalledOnce();await item.controller.end();});
 it("rejects a non-admin speaker before transcription and chat",async()=>{const verify=vi.fn(async()=>({matched:false}));const transcribe=vi.fn();const ask=vi.fn();const item=recorded({verify,ask,bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});await item.controller.start();item.capture();await item.controller.finish();expect(verify).toHaveBeenCalledOnce();expect(transcribe).not.toHaveBeenCalled();expect(ask).not.toHaveBeenCalled();await item.controller.end();});
 it("continuous VAD accepts only after matching speaker and rearms after rejection",async()=>{const verify=vi.fn(async()=>({matched:false}));const transcribe=vi.fn();const item=recorded({continuous:true,verify,bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});await item.controller.start();for(let i=0;i<8;i++)item.capture();for(let i=0;i<4;i++)item.capture(true);for(let i=0;i<12;i++)await Promise.resolve();expect(verify).toHaveBeenCalledOnce();expect(transcribe).not.toHaveBeenCalled();expect(item.controller.phase).toBe("recording");await item.controller.end();});
 it("checks short wake PCM without fabricating speech and shows bounded rejection notice before rearming",async()=>{
  vi.useFakeTimers();const states:Parameters<LocalVoiceOptions["onState"]>[0][]=[];const verify=vi.fn(async(_wav:string,_id:string)=>({matched:false,reason:"uncertain"}));const transcribe=vi.fn();const ask=vi.fn();const item=recorded({continuous:true,verify,ask,onState:state=>states.push(state),bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});
  await item.controller.start();for(let i=0;i<2;i++)item.capture();for(let i=0;i<6;i++)item.capture(true);for(let i=0;i<16;i++)await Promise.resolve();
  expect(verify).toHaveBeenCalledOnce();const bytes=Uint8Array.from(atob(verify.mock.calls[0][0]),c=>c.charCodeAt(0));expect(new DataView(bytes.buffer).getUint32(40,true)).toBe(32768*2);expect(item.controller.phase).toBe("recording");expect(states.at(-1)?.notice).toBe("speaker-uncertain");expect(transcribe).not.toHaveBeenCalled();expect(ask).not.toHaveBeenCalled();
  await vi.advanceTimersByTimeAsync(1000);item.capture(true);await vi.advanceTimersByTimeAsync(1000);item.capture(true);await vi.advanceTimersByTimeAsync(1000);item.capture(true);await vi.advanceTimersByTimeAsync(1000);expect(states.at(-1)?.notice).toBeUndefined();await item.controller.end();expect(vi.getTimerCount()).toBe(0);
 });
 it("does not reveal arbitrary backend reason text in speaker notices",()=>{expect(speakerNotice("private-profile-secret")).toBe("speaker-different");expect(speakerNotice("too-short")).toBe("speaker-too-short");});
 it("cancels a pending speaker check and ignores its late match",async()=>{let done:(value:{matched:boolean})=>void=()=>{};const verify=vi.fn(()=>new Promise<{matched:boolean}>(resolve=>done=resolve));const transcribe=vi.fn();const item=recorded({verify,bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});await item.controller.start();item.capture();const finish=item.controller.finish();for(let i=0;i<4;i++)await Promise.resolve();await item.controller.end();done({matched:true});await finish;expect(transcribe).not.toHaveBeenCalled();expect(item.controller.active).toBe(false);});
 it("encodes a bounded mono 16k PCM WAV with proper header and clamped samples",()=>{const wav=pcmWav(new Float32Array([2,-2,.5,0]),16000);const view=new DataView(wav.buffer);expect(String.fromCharCode(...wav.subarray(0,4))).toBe("RIFF");expect(view.getUint32(24,true)).toBe(16000);expect(view.getUint16(22,true)).toBe(1);expect(view.getInt16(44,true)).toBe(32767);expect(view.getInt16(46,true)).toBe(-32768);expect(view.getUint32(40,true)).toBe(8);});
 it("resamples 48k capture to 16k and rejects overlong recording",()=>{expect(pcmWav(new Float32Array(48000),48000).length).toBe(32044);expect(()=>pcmWav(new Float32Array(16000*31),16000)).toThrow("local-duration");});
 it("stops microphone tracks arriving after cancellation without creating an audio context",async()=>{let resolve:(value:MediaStream)=>void=()=>{};const stop=vi.fn();const context=vi.fn();const states:string[]=[];const controller=new LocalVoiceController({media:{getUserMedia:()=>new Promise(done=>resolve=done)},context,ask:async()=>"",onState:s=>states.push(s.phase),bridge:{cancel:async()=>{},transcribe:vi.fn(),speak:vi.fn()}});const starting=controller.start();expect(controller.active).toBe(true);await controller.end();resolve({getTracks:()=>[{stop}]} as unknown as MediaStream);await starting;expect(stop).toHaveBeenCalledOnce();expect(context).not.toHaveBeenCalled();expect(controller.active).toBe(false);expect(states).toEqual(["preparing","idle"]);});
 it("reports denied microphone without calling transcription or chat",async()=>{const ask=vi.fn();const transcribe=vi.fn();const states:string[]=[];const controller=new LocalVoiceController({media:{getUserMedia:async()=>{throw new DOMException("Permission denied","NotAllowedError");}},ask,onState:s=>states.push(s.phase),bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});await controller.start();expect(states).toEqual(["preparing","error"]);expect(transcribe).not.toHaveBeenCalled();expect(ask).not.toHaveBeenCalled();});
 it("closes microphone and suppresses silence before native transcription",async()=>{const transcribe=vi.fn();const item=recorded({bridge:{cancel:async()=>{},transcribe,speak:vi.fn()}});await item.controller.start();item.capture(true);await item.controller.finish();expect(item.stop).toHaveBeenCalledOnce();expect(item.close).toHaveBeenCalledOnce();expect(transcribe).not.toHaveBeenCalled();expect(item.controller.phase).toBe("error");});
 it("ignores transcription arriving after cancel and cancels only its own native request",async()=>{let resolve:(value:{text:string})=>void=()=>{};const transcribe=vi.fn((_wav:string,_id:string)=>new Promise<{text:string}>(done=>resolve=done));const cancel=vi.fn(async()=>{});const ask=vi.fn();const speak=vi.fn();const item=recorded({ask,bridge:{cancel,transcribe,speak}});await item.controller.start();item.capture();const finish=item.controller.finish();await Promise.resolve();await Promise.resolve();expect(transcribe).toHaveBeenCalledOnce();const id=transcribe.mock.calls[0]?.[1];await item.controller.end();resolve({text:"late transcript"});await finish;expect(cancel).toHaveBeenCalledWith(id);expect(ask).not.toHaveBeenCalled();expect(speak).not.toHaveBeenCalled();});
 it("cancels an active chat before cleanup awaits and never speaks its stale answer",async()=>{let resolve:(text:string)=>void=()=>{};const ask=vi.fn(()=>new Promise<string>(done=>resolve=done));const cancelAsk=vi.fn(async()=>{});const speak=vi.fn();const item=recorded({ask,cancelAsk,bridge:{cancel:async()=>{},transcribe:async()=>({text:"سلام"}),speak}});await item.controller.start();item.capture();const finish=item.controller.finish();for(let i=0;i<5;i++)await Promise.resolve();expect(ask).toHaveBeenCalledWith("سلام");const ending=item.controller.end();expect(cancelAsk).toHaveBeenCalledOnce();await ending;resolve("stale answer");await finish;expect(speak).not.toHaveBeenCalled();});
 it("rejects nonfinite PCM samples instead of silently sending corrupted audio",()=>{expect(()=>pcmWav(new Float32Array([NaN]),16000)).toThrow("local-audio-invalid");});
 it("an old resume continuation never closes a newer recording",async()=>{
  let resumeOld:()=>void=()=>{};const oldStop=vi.fn();const newStop=vi.fn();const oldClose=vi.fn(async()=>{});const newClose=vi.fn(async()=>{});
  const processor={connect:vi.fn(),disconnect:vi.fn(),onaudioprocess:null};
  const source={connect:vi.fn(),disconnect:vi.fn()};
  const oldContext={sampleRate:16000,state:"running",resume:()=>new Promise<void>(resolve=>resumeOld=resolve),close:oldClose} as unknown as AudioContext;
  const newContext={sampleRate:16000,state:"running",resume:async()=>{},close:newClose,createMediaStreamSource:()=>source,createScriptProcessor:()=>processor,destination:{}} as unknown as AudioContext;
  let call=0;const controller=new LocalVoiceController({media:{getUserMedia:async()=>{const stop=call++===0?oldStop:newStop;return{getTracks:()=>[{stop}]} as unknown as MediaStream;}},context:vi.fn().mockReturnValueOnce(oldContext).mockReturnValueOnce(newContext),ask:async()=>"",onState:()=>{},bridge:{cancel:async()=>{},transcribe:vi.fn(),speak:vi.fn()}});
  const first=controller.start();await Promise.resolve();await controller.end();await controller.start();expect(controller.phase).toBe("recording");resumeOld();await first;expect(newStop).not.toHaveBeenCalled();expect(newClose).not.toHaveBeenCalled();expect(controller.phase).toBe("recording");await controller.end();
 });
 it("concurrent old ends cannot reset the phase of a restarted recording",async()=>{
  let closed:()=>void=()=>{};const old=recorded();const oldContext={sampleRate:16000,state:"running",resume:async()=>{},close:()=>new Promise<void>(resolve=>closed=resolve),createMediaStreamSource:()=>({connect:vi.fn(),disconnect:vi.fn()}),createScriptProcessor:()=>old.processor,destination:{}} as unknown as AudioContext;
  const next=recorded();let index=0;const controller=new LocalVoiceController({media:{getUserMedia:async()=>({getTracks:()=>[{stop:vi.fn()}]} as unknown as MediaStream)},context:()=>index++===0?oldContext:({sampleRate:16000,state:"running",resume:async()=>{},close:next.close,createMediaStreamSource:()=>({connect:vi.fn(),disconnect:vi.fn()}),createScriptProcessor:()=>next.processor,destination:{}} as unknown as AudioContext),ask:async()=>"",onState:()=>{},bridge:{cancel:async()=>{},transcribe:vi.fn(),speak:vi.fn()}});
  await controller.start();const first=controller.end();await controller.end();await controller.start();closed();await first;expect(controller.phase).toBe("recording");expect(next.close).not.toHaveBeenCalled();await controller.end();
 });
 it("plays native speech through a Blob URL and revokes it after playback",async()=>{
  const create=vi.fn(()=>"blob:test-local-audio");const revoke=vi.fn();const OriginalURL=URL;class TestURL extends OriginalURL{static override createObjectURL=create;static override revokeObjectURL=revoke;}vi.stubGlobal("URL",TestURL);
  const audio={src:"",onended:null as (()=>void)|null,onerror:null,play:vi.fn(async()=>{}),pause:vi.fn(),removeAttribute:vi.fn(),load:vi.fn()} as unknown as HTMLAudioElement;
  const bytes=pcmWav(new Float32Array(160),16000);const wavBase64=btoa(String.fromCharCode(...bytes));const item=recorded({audio:()=>audio,bridge:{cancel:async()=>{},transcribe:async()=>({text:"سلام"}),speak:async()=>({wavBase64})}});
  await item.controller.start();item.capture();const finish=item.controller.finish();for(let i=0;i<8;i++)await Promise.resolve();expect(audio.src).toBe("blob:test-local-audio");expect(audio.play).toHaveBeenCalledOnce();audio.onended?.(new Event("ended"));await finish;expect(revoke).toHaveBeenCalledWith("blob:test-local-audio");expect(audio.pause).toHaveBeenCalledOnce();expect(item.controller.phase).toBe("idle");vi.unstubAllGlobals();
 });
});
