import {describe,it,expect,vi,beforeEach} from "vitest";
const mocks=vi.hoisted(()=>({decide:vi.fn(),pending:vi.fn(),clear:vi.fn(async()=>{})}));
vi.mock("../core/bridge",()=>({IS_TAURI:false,onEvent:async()=>()=>{},Bridge:{log:vi.fn()}}));
vi.mock("../core/bridge-local",()=>({BridgeLocal:{proposalDecide:mocks.decide,proposalPending:mocks.pending,proposalClear:mocks.clear}}));
vi.mock("../core/state",()=>({State:{notify:vi.fn()}}));
import {setVoiceProposal,voiceProposalCard,decideVoiceProposal,voiceProposal,clearVoiceProposal} from "./voice-proposals";
import {setLanguage} from "../core/i18n";
const proposal={id:"proposal-1",kind:"task" as const,text:"Prepare the report"};
beforeEach(()=>{vi.clearAllMocks();setLanguage("en");setVoiceProposal(proposal);mocks.pending.mockResolvedValue({proposal});});
describe("voice proposal confirmation",()=>{
 it("keeps the complete maximum note keyboard reachable with independent decision controls",()=>{const text="یادداشت طولانی ".repeat(120).slice(0,1500);setVoiceProposal({id:"long-note",kind:"note",text});const card=voiceProposalCard();const body=card.el.querySelector<HTMLElement>(".voice-proposal-text")!;expect(body.textContent).toBe(text);expect(body.tabIndex).toBe(0);expect(card.el.querySelector(".voice-proposal-actions")!.contains(body)).toBe(false);expect([...card.el.querySelectorAll<HTMLButtonElement>("button")].every(button=>!button.disabled)).toBe(true);card.dispose();});
 it("renders pending truthful text and never saves until a click",async()=>{const card=voiceProposalCard();expect(card.el.textContent).toContain("Nothing has been saved");expect(mocks.decide).not.toHaveBeenCalled();mocks.decide.mockResolvedValue({text:"Task saved"});card.el.querySelector<HTMLButtonElement>("button")!.click();await vi.waitFor(()=>expect(card.el.textContent).toContain("Task saved"));expect(mocks.decide).toHaveBeenCalledExactlyOnceWith(proposal.id,true,"en");expect(voiceProposal()).toBeNull();card.dispose();});
 it("consumes concurrent decisions once and rejection does not mean saved",async()=>{let finish:(result:{text:string})=>void=()=>{};mocks.decide.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const first=decideVoiceProposal(false);await decideVoiceProposal(true);expect(mocks.decide).toHaveBeenCalledOnce();finish({text:"Not saved"});await first;expect(mocks.decide).toHaveBeenCalledWith(proposal.id,false,"en");expect(voiceProposal()).toBeNull();});
 it("retains retryable proposals after storage failure and explains expired proposals",async()=>{const card=voiceProposalCard();mocks.decide.mockRejectedValue(new Error("planner-storage"));await decideVoiceProposal(true);expect(voiceProposal()).toEqual(proposal);expect(card.el.textContent).toContain("try again");expect(card.el.querySelector<HTMLButtonElement>("button")!.disabled).toBe(false);mocks.decide.mockRejectedValue(new Error("voice-proposal-expired"));mocks.pending.mockResolvedValue({proposal:null});await decideVoiceProposal(true);expect(voiceProposal()).toBeNull();expect(card.el.textContent).toContain("no longer pending");card.dispose();});
 it("shares pending state across rebuilt cards and clears on off",async()=>{const first=voiceProposalCard();first.dispose();const next=voiceProposalCard();expect(next.el.textContent).toContain(proposal.text);await clearVoiceProposal();expect(mocks.clear).toHaveBeenCalledOnce();expect(next.el.hidden).toBe(true);next.dispose();});
});
