import {describe,it,expect,vi,beforeEach,afterEach} from "vitest";
const mocks=vi.hoisted(()=>({ask:undefined as undefined|((query:string)=>Promise<string>),desktop:vi.fn(),chat:vi.fn(),status:vi.fn(),brain:vi.fn(),pending:vi.fn(),analyze:vi.fn()}));
vi.mock("../local/global-voice",()=>({bindGlobalVoiceChat:(ask:(query:string)=>Promise<string>)=>{mocks.ask=ask;}}));
vi.mock("./assistant-controls",()=>({createAssistantControls:()=>({el:document.createElement("div"),sync:()=>{},dispose:()=>{}})}));
vi.mock("../core/bridge",async importOriginal=>{const actual=await importOriginal<typeof import("../core/bridge")>();return{...actual,IS_TAURI:true,onChatStream:async()=>()=>{},onRoadeepBalance:async()=>()=>{},onEvent:async()=>()=>{},Bridge:{...actual.Bridge,chatSend:mocks.chat,chatToolsState:async()=>({available:false,on:false,count:0}),chatTurnState:async()=>({busy:false,turn:null}),log:async()=>{},roadeepModels:async()=>[],chatModels:async()=>[],logError:async()=>{},openExternal:async()=>{}}};});
vi.mock("../core/bridge-local",()=>({BridgeLocal:{desktopVoiceTry:mocks.desktop,status:mocks.status,chat:mocks.brain,cancel:async()=>{},proposalPending:mocks.pending,analyzeVoice:mocks.analyze},onLocalRuntimeProgress:async()=>()=>{}}));
import {buildPrompt} from "./chat";
import {State} from "../core/state";
import {RoadeepError} from "../core/bridge";
import {setLanguage} from "../core/i18n";
const ready={ready:true,enabled:true,phase:"ready",component:"",downloaded:0,total:0,error:null};
beforeEach(()=>{vi.clearAllMocks();setLanguage("en");State.chatHistory=[];State.droppedFile=null;State.settings.chatAgent=null;State.roadeep.signedIn=false;State.view="prompt";State.mode="expanded";mocks.analyze.mockResolvedValue({route:"chat",text:""});mocks.pending.mockResolvedValue({proposal:null});mocks.status.mockResolvedValue(ready);mocks.brain.mockResolvedValue({route:"cloud",text:"",reason:"tools-or-current-information"});mocks.desktop.mockResolvedValue({handled:false,text:""});mocks.chat.mockResolvedValue({text:"Task complete",threadId:null,messageId:null});});
afterEach(()=>{document.body.replaceChildren();});
describe("the real voice-bound chat submit",()=>{
 it("never launches desktop actions, admin analysis or voice proposals for the live voice turn",async()=>{State.roadeep.signedIn=true;buildPrompt(()=>{});mocks.desktop.mockResolvedValue({handled:true,text:"This PC opened",action:"this_pc"});mocks.pending.mockResolvedValue({proposal:{id:"p",kind:"task",text:"x"}});expect(await mocks.ask!("open This PC")).toBe("Task complete");expect(mocks.desktop).not.toHaveBeenCalled();expect(mocks.analyze).not.toHaveBeenCalled();expect(mocks.pending).not.toHaveBeenCalled();});
 it("passes voice authority restriction on an unknown cloud task",async()=>{State.roadeep.signedIn=true;State.chatHistory=[{id:1,role:"user",content:"My name is Amir"},{id:2,role:"assistant",content:"Hello Amir",origin:"local"}];buildPrompt(()=>{});expect(await mocks.ask!("plan a task")).toBe("Task complete");expect(mocks.chat.mock.calls[0][4]).toBe(true);expect(mocks.chat.mock.calls[0][0]).toContain("My name is Amir");expect(mocks.chat.mock.calls[0][0]).toContain("untrusted");expect(mocks.chat.mock.calls[0][0].match(/plan a task/g)).toHaveLength(1);});
 it("returns policy failures as truthful app messages for speech",async()=>{State.roadeep.signedIn=true;buildPrompt(()=>{});mocks.chat.mockRejectedValue(new Error("voice-sensitive-action-blocked"));expect(await mocks.ask!("send money")).toContain("blocked");expect(mocks.desktop).not.toHaveBeenCalled();});
 it("keeps typed requests out of the voice fast path and sends the default authority",async()=>{State.roadeep.signedIn=true;const view=buildPrompt(()=>{});document.body.append(view.el);view.sync();await new Promise(resolve=>setTimeout(resolve,0));const input=view.el.querySelector<HTMLTextAreaElement>("textarea")!;input.value="plan a typed task";view.el.querySelector<HTMLButtonElement>(".send-btn")!.click();await new Promise(resolve=>setTimeout(resolve,0));expect(mocks.desktop).not.toHaveBeenCalled();expect(mocks.chat.mock.calls[0][4]).toBe(false);});
 it("keeps the displayed typed thread model when voice uses a fresh thread",async()=>{State.roadeep.signedIn=true;const view=buildPrompt(()=>{});document.body.append(view.el);view.sync();await new Promise(resolve=>setTimeout(resolve,0));mocks.chat.mockResolvedValueOnce({text:"Typed answer",threadId:"typed-thread",messageId:"typed",model:"typed-model"});const input=view.el.querySelector<HTMLTextAreaElement>("textarea")!;input.value="typed request";view.el.querySelector<HTMLButtonElement>(".send-btn")!.click();await vi.waitFor(()=>expect(State.chatHistory.at(-1)?.content).toBe("Typed answer"));view.sync();expect(view.el.querySelector(".chat-model-current")?.textContent).toContain("typed-model");mocks.chat.mockResolvedValueOnce({text:"Voice answer",threadId:"voice-thread",messageId:"voice",model:"voice-model"});await mocks.ask!("voice request");view.sync();expect(view.el.querySelector(".chat-model-current")?.textContent).toContain("typed-model");expect(view.el.querySelector(".chat-model-current")?.textContent).not.toContain("voice-model");});
 it("preserves typed local history for its later cloud handoff",async()=>{State.roadeep.signedIn=true;const view=buildPrompt(()=>{});document.body.append(view.el);view.sync();await new Promise(resolve=>setTimeout(resolve,0));const input=view.el.querySelector<HTMLTextAreaElement>("textarea")!;mocks.brain.mockResolvedValueOnce({route:"local",text:"Local typed answer",reason:"local-small-task"});input.value="remember typed note";view.el.querySelector<HTMLButtonElement>(".send-btn")!.click();await vi.waitFor(()=>expect(State.chatHistory.at(-1)?.content).toBe("Local typed answer"));await mocks.ask!("voice cloud request");input.value="typed cloud request";view.el.querySelector<HTMLButtonElement>(".send-btn")!.click();await vi.waitFor(()=>expect(mocks.chat).toHaveBeenCalledTimes(2));expect(mocks.chat.mock.calls[1][0]).toContain("remember typed note");expect(mocks.chat.mock.calls[1][4]).toBe(false);});
 it("does not upload a typed drop or inherit the selected agent for voice",async()=>{State.roadeep.signedIn=true;State.droppedFile={name:"private.txt",path:"C:/private.txt"};State.settings.chatAgent="typed-agent";buildPrompt(()=>{});await mocks.ask!("hello");expect(mocks.brain.mock.calls[0][2]).toBe(false);expect(mocks.chat.mock.calls[0][1]).toBeNull();expect(mocks.chat.mock.calls[0][2]).toBeNull();expect(State.droppedFile).toEqual({name:"private.txt",path:"C:/private.txt"});});
 it("returns the chat answer itself for the live voice to speak",async()=>{State.roadeep.signedIn=true;buildPrompt(()=>{});mocks.chat.mockResolvedValue({text:"Here is the plan",threadId:null,messageId:null});const reply=await mocks.ask!("make a plan");expect(reply).toBe("Here is the plan");expect(State.chatHistory.at(-1)?.content).toBe(reply);});
 it("updates expired session state while returning a spoken sign-in explanation",async()=>{State.roadeep.signedIn=true;buildPrompt(()=>{});mocks.chat.mockRejectedValue(new RoadeepError({code:"SESSION_EXPIRED",message:"expired",status:401,retryAfter:null,requestId:"mock"}));expect(await mocks.ask!("plan a task")).toContain("Sign in");expect(State.roadeep.signedIn).toBe(false);expect(State.roadeep.expired).toBe(true);});
 it("does not speak a completed answer after Stop was pressed",async()=>{State.roadeep.signedIn=true;const view=buildPrompt(()=>{});document.body.append(view.el);let fail:(error:unknown)=>void=()=>{};mocks.chat.mockImplementationOnce(()=>new Promise((_,reject)=>fail=reject));const pending=mocks.ask!("plan a task");await vi.waitFor(()=>expect(mocks.chat).toHaveBeenCalledOnce());view.el.querySelector<HTMLButtonElement>(".send-btn")!.click();fail(new RoadeepError({code:"CANCELLED",message:"cancelled",status:0,retryAfter:null,requestId:"mock"}));expect(await pending.catch(()=>"")).not.toBe("Task complete");expect(State.chatHistory.some(message=>message.content==="Task complete")).toBe(false);});
 it("does not run twice while a live voice request is pending",async()=>{State.roadeep.signedIn=true;buildPrompt(()=>{});let finish:(value:{text:string;threadId:null;messageId:null})=>void=()=>{};mocks.chat.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const first=mocks.ask!("plan a task");await expect(mocks.ask!("plan a task")).rejects.toThrow("busy");await vi.waitFor(()=>expect(mocks.chat).toHaveBeenCalledOnce());finish({text:"Task complete",threadId:null,messageId:null});await first;expect(mocks.chat).toHaveBeenCalledOnce();});

});
