const { chromium } = require('C:/Users/Amir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const path=require('path');
const assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.addInitScript(()=>{const raf=window.requestAnimationFrame.bind(window);window.__rafCount=0;window.requestAnimationFrame=callback=>{window.__rafCount++;return raf(callback);};});
 await page.goto('http://127.0.0.1:1420/?view=empty&zoom=1&idle=1');
 await page.waitForTimeout(1000);
 await page.evaluate(async()=>{
  const resource=part=>performance.getEntriesByType('resource').find(e=>e.name.includes(part)).name;
  const {Island}=await import(resource('/src/island/island.ts'));
  const {State}=await import(resource('/src/core/state.ts'));
  const run=Island.prototype.ensureRunning;
  Island.prototype.ensureRunning=function(){window.__testIsland=this;return run.call(this);};
  window.__testState=State;State.notify();
 });
 await page.waitForFunction(()=>!!window.__testIsland);
 await page.waitForTimeout(4500);
 const live=[];
 for(const [state,expected] of [['question','curious'],['error','shake'],['approval','bounce'],['finished','spin']]) {
  await page.evaluate(state=>{const s=window.__testState;s.stateOverride=state;s.notify();},state);
  await page.waitForFunction(expected=>window.__testIsland.engine.activeAnimation===expected,expected);
  const actual=await page.evaluate(()=>window.__testIsland.engine.activeAnimation);
  assert.equal(actual,expected);live.push({state,animation:actual});
  await page.waitForTimeout(150);
 }
 await page.evaluate(()=>{window.__testState.stateOverride=null;window.__testState.notify();window.__testIsland.fsm.forceHidden();});
 await page.waitForTimeout(1600);
 const first=await page.evaluate(()=>({count:window.__rafCount,mode:window.__testState.mode,running:window.__testIsland.running}));
 await page.waitForTimeout(1000);
 const second=await page.evaluate(()=>({count:window.__rafCount,mode:window.__testState.mode,running:window.__testIsland.running}));
 assert.equal(second.mode,'hidden');assert.equal(second.running,false);assert.equal(second.count,first.count);
 await page.goto('http://127.0.0.1:1420/dev/character-preview.html?animation=bounce');
 await page.waitForFunction(()=>!!window.characterPreview);
 const captures=await page.evaluate(()=>window.characterPreview.renderAt(390));
 assert(captures.filter(p=>p.name==='bounce').every(p=>p.pose.y<-.2));
 await page.locator('#reduced').check();
 const reduced=await page.evaluate(()=>window.characterPreview.renderAt(390));
 assert(reduced.every(p=>p.pose.x===0&&p.pose.y===0&&p.pose.scaleX===1&&p.pose.scaleY===1&&p.pose.roll===0));
 await page.locator('#reduced').uncheck();
 await page.locator('#pause').focus();
 await page.keyboard.press('Enter');
 await page.keyboard.press('Tab');
 const focused=await page.evaluate(()=>document.activeElement.id);
 assert.equal(focused,'reduced');
 for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.goto('http://127.0.0.1:1420/dev/character-preview.html');
 await page.waitForFunction(()=>!!window.characterPreview);
 await page.locator('#greet').click();await page.waitForTimeout(120);await page.locator('#pause').click();
 const paused=await page.locator('#hero canvas').evaluate(c=>c.toDataURL());
 const pausedClock=await page.locator('#clock').textContent();
 await page.waitForTimeout(650);
 assert.equal(await page.locator('#hero canvas').evaluate(c=>c.toDataURL()),paused);
 assert.equal(await page.locator('#clock').textContent(),pausedClock);
 await page.locator('#pause').click();await page.waitForTimeout(350);
 assert.notEqual(await page.locator('#hero canvas').evaluate(c=>c.toDataURL()),paused);
 await page.locator('#context').selectOption('working');await page.waitForTimeout(4300);
 const contextClock=Number((await page.locator('#clock').textContent()).split(' ')[0]);
 assert(contextClock>4000);await page.waitForTimeout(150);
 assert(Number((await page.locator('#clock').textContent()).split(' ')[0])>contextClock);
 await page.locator('#context').selectOption('idle');await page.waitForTimeout(4300);
 assert.equal(await page.locator('#pause').textContent(),'پایان پخش');
 assert(await page.locator('#pause').isDisabled());
 await page.locator('#replay').click();await page.waitForTimeout(150);
 assert(Number((await page.locator('#clock').textContent()).split(' ')[0])<1000);
 assert.deepEqual(errors,[]);
 const report={live,hidden:{first,second,extraFrames:second.count-first.count},reduced:true,keyboard:true,timerPauseResume:true,liveContextContinuation:true,completedReplay:true,responsiveWidths:[320,375,768,1440],errors};
 fs.writeFileSync(path.join(__dirname,'browser-verification.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
