// Roadeep managed OpenCode adapter v1. Generated by Roadeep settings; requires the documented OpenCode V2 plugin API.
import { Plugin } from "@opencode/plugin";
import { spawn, type ChildProcess } from "node:child_process";

const relayPath = "__ROADEEP_RELAY__";
const lifecycle: Readonly<Record<string, string>> = {
  "session.created": "session.created", "session.deleted": "session.deleted",
  "session.idle": "session.idle", "session.error": "session.error",
  "permission.asked": "permission.asked",
};
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const text = (value: unknown): string | undefined => typeof value === "string" && value.length > 0 && value.length <= 200 && !/[\x00-\x1f]/.test(value) ? value : undefined;

export default Plugin.define({
  id: "roadeep.coding-activity",
  async setup(ctx) {
    const controller = new AbortController();
    const children = new Map<ChildProcess, ReturnType<typeof setTimeout>>();
    const sessions = new Set<string>();
    const registrations: { dispose(): Promise<void> | void }[] = [];
    let closed = false;
    let warningAt = 0;
    const warning = (code: string) => {
      if (Date.now() - warningAt > 10_000) { console.warn(`[Roadeep hook] ${code}`); warningAt = Date.now(); }
    };
    const notify = (event: string, value: unknown, streamDirectory?: unknown, fromStream = false) => {
      if (closed || children.size >= 16) { if (!closed) warning("queue-full"); return; }
      const input = record(value);
      const info = record(input.info);
      const metadata = record(input.context);
      const session = text(input.sessionID) ?? text(input.session_id) ?? text(info.id) ?? text(metadata.sessionID);
      if (!session) { warning("identity-unavailable"); return; }
      const directory = streamDirectory ?? info.directory ?? input.cwd ?? input.directory;
      const comparable = (path: string) => path.replace(/\\/g, "/").replace(/\/$/, "").toLowerCase();
      if (typeof directory === "string" && comparable(directory) !== comparable(ctx.location.directory)) return;
      // The stream is server-wide. Do not attribute another project's session to this plugin's location.
      if (fromStream && typeof directory !== "string" && !sessions.has(session)) return;
      sessions.add(session);
      if (sessions.size > 128) sessions.delete(sessions.values().next().value!);
      // Structural metadata only: no tool arguments, prompt, output, transcript, error detail or environment.
      const payload = JSON.stringify({ session_id: session, cwd: ctx.location.directory,
        tool_name: text(input.tool), tool_use_id: text(input.callID) ?? text(input.id),
        notification_type: event === "permission.asked" ? "permission_prompt" : undefined,
      });
      if (payload.length > 4096) { warning("payload-too-large"); return; }
      try {
        const child = spawn(relayPath, ["--provider", "opencode", event], { shell: false, windowsHide: true, stdio: ["pipe", "ignore", "ignore"] });
        const timer = setTimeout(() => { children.delete(child); child.kill(); warning("relay-timeout"); }, 2000);
        children.set(child, timer);
        const release = () => { clearTimeout(timer); children.delete(child); };
        child.once("error", () => { release(); warning("relay-unavailable"); });
        child.once("exit", (code) => { release(); if (code !== 0 && !closed) warning("relay-failed"); });
        child.stdin?.on("error", () => { release(); child.kill(); warning("relay-input-failed"); });
        child.stdin?.end(payload);
      } catch { warning("relay-unavailable"); }
    };
    const dispose = async () => {
      if (closed) return;
      closed = true; controller.abort();
      for (const [child, timer] of children) { clearTimeout(timer); child.kill(); }
      children.clear();
      for (const registration of registrations) { try { await registration.dispose(); } catch { warning("cleanup-failed"); } }
    };
    try {
      registrations.push(await ctx.session.hook("prompt", (event) => { notify("session.prompt", event); }));
      registrations.push(await ctx.tool.hook("execute.before", (event) => { notify("tool.execute.before", event); }));
      registrations.push(await ctx.tool.hook("execute.after", (event) => { notify(event.status === "error" ? "tool.execute.failed" : "tool.execute.after", event); }));
      void (async () => {
        try {
          for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
            const source = record(event);
            const data = source.properties ?? source.data;
            const name = typeof source.type === "string" ? lifecycle[source.type] : undefined;
            const directory = record(source.location).directory;
            if (name) notify(name, data, directory, true);
            if (source.type === "session.status" && record(record(data).status).type === "idle") notify("session.idle", data, directory, true);
          }
        } catch { if (!closed) warning("event-stream-unavailable"); }
      })();
    } catch { warning("plugin-api-unavailable"); await dispose(); }
    return dispose;
  },
});
